defaults:
  - _self_

method: semi-supervised-ensemble

train:
  total_epochs: 4000
  validation_interval: 10
init:
  _target_: trainer.SemiSupervisedEnsemble
  supervised_criterion:
    _target_: torch.nn.MSELoss
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.001 # TODO: change 4
    weight_decay: 0.005 # TODO: change 5
  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    _partial_: true
    step_size: 100 # TODO: change 6
    gamma: 0.95 # TODO: change 7
  rampup_scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    _partial_: true
    step_size: 20  # Increase unsupervised weight every 20 epochs
    gamma: 1.5     # Multiply by 1.5 each step (will be capped at unsupervised_weight)
    
  unsupervised_weight: 1.0  # Weight for unsupervised consistency loss (default enabled)
  use_mean_teacher: true     # Use Mean Teacher (EMA teacher models) for pseudo-labels
  ema_decay: 0.999           # EMA decay rate for teacher model updates